/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { RoleType, CompanyTier, CompensationRecord, LevelMapping, LocationInfo } from "./types.ts";

export const STAGE_LOCATIONS: LocationInfo[] = [
  { name: "Bangalore, IN", country: "India", costOfLivingIndex: 100, currency: "INR", symbol: "₹", multiplier: 1.0 },
  { name: "Mumbai, IN", country: "India", costOfLivingIndex: 115, currency: "INR", symbol: "₹", multiplier: 1.15 },
  { name: "Delhi NCR, IN", country: "India", costOfLivingIndex: 108, currency: "INR", symbol: "₹", multiplier: 1.08 },
  { name: "Hyderabad, IN", country: "India", costOfLivingIndex: 92, currency: "INR", symbol: "₹", multiplier: 0.92 },
  { name: "Pune, IN", country: "India", costOfLivingIndex: 90, currency: "INR", symbol: "₹", multiplier: 0.90 },
  { name: "Chennai, IN", country: "India", costOfLivingIndex: 88, currency: "INR", symbol: "₹", multiplier: 0.88 },
  { name: "Gurgaon, IN", country: "India", costOfLivingIndex: 105, currency: "INR", symbol: "₹", multiplier: 1.05 },
  { name: "Noida, IN", country: "India", costOfLivingIndex: 95, currency: "INR", symbol: "₹", multiplier: 0.95 },
  { name: "Kolkata, IN", country: "India", costOfLivingIndex: 82, currency: "INR", symbol: "₹", multiplier: 0.82 }
];

export const STANDARD_LEVELS = [
  { value: "L1", title: "Entry / Associate" },
  { value: "L2", title: "Mid-Level / Software Engineer II" },
  { value: "L3", title: "Senior / Senior Specialist" },
  { value: "L4", title: "Staff / Principal Specialist" },
  { value: "L5", title: "Senior Staff / Director equivalent" },
  { value: "L6", title: "Principal / Senior Director" },
  { value: "L7", title: "Distinguished Engineer / VP equivalent" },
  { value: "L8", title: "Fellow / Executive equivalent" }
];

export const LEVEL_MATRICES: LevelMapping[] = [
  {
    standardLevel: "L1",
    title: "Entry / Associate",
    google: "L3 (Software Engineer I)",
    meta: "E3 (Rotational Engineer)",
    apple: "ICT2 (Junior Engineer)",
    amazon: "L4 (SDE I)",
    microsoft: "59/60 (SDE)",
    netflix: "Entry Engineer",
    flipkart: "SDE I"
  },
  {
    standardLevel: "L2",
    title: "Mid-Level / SWE II",
    google: "L4 (Software Engineer II)",
    meta: "E4 (Software Engineer)",
    apple: "ICT3 (Software Engineer)",
    amazon: "L5 (SDE II)",
    microsoft: "61/62 (SDE II)",
    netflix: "Mid Engineer",
    flipkart: "SDE II"
  },
  {
    standardLevel: "L3",
    title: "Senior / Senior Specialist",
    google: "L5 (Senior Software Engineer)",
    meta: "E5 (Senior Software Engineer)",
    apple: "ICT4 (Senior Software Engineer)",
    amazon: "L6 (SDE III / Senior SDE)",
    microsoft: "63/64 (Senior SDE)",
    netflix: "Senior Engineer",
    flipkart: "SDE III"
  },
  {
    standardLevel: "L4",
    title: "Staff / Principal",
    google: "L6 (Staff Software Engineer)",
    meta: "E6 (Staff Software Engineer)",
    apple: "ICT5 (Staff Software Engineer)",
    amazon: "L7 (Principal SDE)",
    microsoft: "65/66 (Principal SDE)",
    netflix: "Staff Engineer",
    flipkart: "Architect / Lead SDE"
  },
  {
    standardLevel: "L5",
    title: "Senior Staff / Lead",
    google: "L7 (Senior Staff Engineer)",
    meta: "E7 (Senior Staff Engineer)",
    apple: "ICT6 (Senior Staff Engineer)",
    amazon: "L8 (Director, SDE)",
    microsoft: "67 (Partner SDE)",
    netflix: "Senior Staff Engineer",
    flipkart: "Senior Architect"
  },
  {
    standardLevel: "L6",
    title: "Principal / Director",
    google: "L8 (Principal Engineer)",
    meta: "E8 (Principal Engineer)",
    apple: "Director (IC or Manager)",
    amazon: "L10 (Distinguished SDE)",
    microsoft: "68+ (Partner SDE II)",
    netflix: "Principal Engineer",
    flipkart: "Principal Architect"
  },
  {
    standardLevel: "L7",
    title: "Distinguished / VP",
    google: "L9 (Distinguished Engineer)",
    meta: "E9 (Distinguished Engineer)",
    apple: "VP / Fellow equivalent",
    amazon: "VP / Distinguished Leader",
    microsoft: "Technical Fellow",
    netflix: "VP equivalent",
    flipkart: "Director of Engineering"
  },
  {
    standardLevel: "L8",
    title: "Fellow / Executive",
    google: "Google Fellow",
    meta: "Meta Fellow",
    apple: "Apple Fellow",
    amazon: "VP/CEO equivalent",
    microsoft: "Distinguished Fellow",
    netflix: "Executive VP",
    flipkart: "VP / Fellow equivalent"
  }
];

export const SEED_COMPENSATIONS: CompensationRecord[] = [
  // Google
  {
    id: "1",
    companyName: "Google",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L3",
    standardLevel: "L1",
    baseSalary: 1800000,
    bonus: 250000,
    equity: 400000,
    totalCompensation: 2450000,
    location: "Bangalore, IN",
    yearsOfExperience: 1,
    yearsAtCompany: 1,
    verified: true,
    submittedAt: "2026-05-12T08:30:00Z"
  },
  {
    id: "2",
    companyName: "Google",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L5",
    standardLevel: "L3",
    baseSalary: 4200000,
    bonus: 600000,
    equity: 1500000,
    totalCompensation: 6300000,
    location: "Hyderabad, IN",
    yearsOfExperience: 6,
    yearsAtCompany: 3,
    verified: true,
    submittedAt: "2026-06-01T14:20:00Z"
  },
  {
    id: "3",
    companyName: "Google",
    tier: CompanyTier.TIER_1,
    role: RoleType.PRODUCT_MANAGER,
    levelCode: "L6",
    standardLevel: "L4",
    baseSalary: 5500000,
    bonus: 1100000,
    equity: 2200000,
    totalCompensation: 8800000,
    location: "Delhi NCR, IN",
    yearsOfExperience: 10,
    yearsAtCompany: 4,
    verified: true,
    submittedAt: "2026-06-15T11:45:00Z"
  },
  // Meta
  {
    id: "4",
    companyName: "Meta",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "E4",
    standardLevel: "L2",
    baseSalary: 2800000,
    bonus: 350000,
    equity: 800000,
    totalCompensation: 3950000,
    location: "Mumbai, IN",
    yearsOfExperience: 3,
    yearsAtCompany: 1.5,
    verified: true,
    submittedAt: "2026-04-10T16:10:00Z"
  },
  {
    id: "5",
    companyName: "Meta",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "E5",
    standardLevel: "L3",
    baseSalary: 4000000,
    bonus: 600000,
    equity: 1600000,
    totalCompensation: 6200000,
    location: "Pune, IN",
    yearsOfExperience: 7,
    yearsAtCompany: 2,
    verified: true,
    submittedAt: "2026-06-20T09:12:00Z"
  },
  {
    id: "6",
    companyName: "Meta",
    tier: CompanyTier.TIER_1,
    role: RoleType.PRODUCT_DESIGNER,
    levelCode: "E5",
    standardLevel: "L3",
    baseSalary: 3600000,
    bonus: 400000,
    equity: 1000000,
    totalCompensation: 5000000,
    location: "Bangalore, IN",
    yearsOfExperience: 8,
    yearsAtCompany: 3,
    verified: false,
    submittedAt: "2026-06-22T17:00:00Z"
  },
  // Amazon
  {
    id: "7",
    companyName: "Amazon",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L4",
    standardLevel: "L1",
    baseSalary: 1500000,
    bonus: 250000,
    equity: 200000,
    totalCompensation: 1950000,
    location: "Chennai, IN",
    yearsOfExperience: 1,
    yearsAtCompany: 1,
    verified: true,
    submittedAt: "2026-05-30T10:05:00Z"
  },
  {
    id: "8",
    companyName: "Amazon",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L6",
    standardLevel: "L3",
    baseSalary: 3800000,
    bonus: 400000,
    equity: 1200000,
    totalCompensation: 5400000,
    location: "Gurgaon, IN",
    yearsOfExperience: 8,
    yearsAtCompany: 4,
    verified: true,
    submittedAt: "2026-06-18T15:30:00Z"
  },
  // Stripe (Tier 2)
  {
    id: "9",
    companyName: "Stripe",
    tier: CompanyTier.TIER_2,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L3",
    standardLevel: "L3",
    baseSalary: 3400000,
    bonus: 300000,
    equity: 1800000,
    totalCompensation: 5500000,
    location: "Bangalore, IN",
    yearsOfExperience: 6,
    yearsAtCompany: 2,
    verified: true,
    submittedAt: "2026-06-19T13:40:00Z"
  },
  {
    id: "10",
    companyName: "Stripe",
    tier: CompanyTier.TIER_2,
    role: RoleType.PRODUCT_MANAGER,
    levelCode: "L2",
    standardLevel: "L2",
    baseSalary: 2400000,
    bonus: 250000,
    equity: 600000,
    totalCompensation: 3250000,
    location: "Pune, IN",
    yearsOfExperience: 4,
    yearsAtCompany: 1,
    verified: false,
    submittedAt: "2026-06-11T12:00:00Z"
  },
  // Uber (Tier 2)
  {
    id: "11",
    companyName: "Uber",
    tier: CompanyTier.TIER_2,
    role: RoleType.DATA_SCIENTIST,
    levelCode: "L5a",
    standardLevel: "L3",
    baseSalary: 3200000,
    bonus: 400000,
    equity: 1000000,
    totalCompensation: 4600000,
    location: "Hyderabad, IN",
    yearsOfExperience: 7,
    yearsAtCompany: 2,
    verified: true,
    submittedAt: "2026-06-14T09:30:00Z"
  },
  // Bangalore, India Hub
  {
    id: "12",
    companyName: "Google",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L4",
    standardLevel: "L2",
    baseSalary: 2800000,
    bonus: 350000,
    equity: 800000,
    totalCompensation: 3950000,
    location: "Bangalore, IN",
    yearsOfExperience: 3,
    yearsAtCompany: 1,
    verified: true,
    submittedAt: "2026-06-03T18:15:00Z"
  },
  {
    id: "13",
    companyName: "Meta",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "E5",
    standardLevel: "L3",
    baseSalary: 4200000,
    bonus: 600000,
    equity: 1500000,
    totalCompensation: 6300000,
    location: "Bangalore, IN",
    yearsOfExperience: 7,
    yearsAtCompany: 2,
    verified: true,
    submittedAt: "2026-06-21T10:45:00Z"
  },
  // Noida, India Hub
  {
    id: "14",
    companyName: "Google",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "L5",
    standardLevel: "L3",
    baseSalary: 4000000,
    bonus: 600000,
    equity: 1200000,
    totalCompensation: 5800000,
    location: "Noida, IN",
    yearsOfExperience: 7,
    yearsAtCompany: 3,
    verified: true,
    submittedAt: "2026-05-22T14:10:00Z"
  },
  {
    id: "15",
    companyName: "Apple",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "ICT4",
    standardLevel: "L3",
    baseSalary: 3800000,
    bonus: 400000,
    equity: 1000000,
    totalCompensation: 5200000,
    location: "Chennai, IN",
    yearsOfExperience: 6,
    yearsAtCompany: 2,
    verified: true,
    submittedAt: "2026-06-05T13:30:00Z"
  },
  // General Enterprise (Tier 3)
  {
    id: "16",
    companyName: "Walmart Global Tech",
    tier: CompanyTier.TIER_3,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "Senior III",
    standardLevel: "L3",
    baseSalary: 2600000,
    bonus: 250000,
    equity: 350000,
    totalCompensation: 3200000,
    location: "Gurgaon, IN",
    yearsOfExperience: 7,
    yearsAtCompany: 2,
    verified: true,
    submittedAt: "2026-06-08T09:00:00Z"
  },
  {
    id: "17",
    companyName: "JP Morgan Chase",
    tier: CompanyTier.TIER_3,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "VP",
    standardLevel: "L4",
    baseSalary: 3500000,
    bonus: 500000,
    equity: 200000,
    totalCompensation: 4200000,
    location: "Kolkata, IN",
    yearsOfExperience: 10,
    yearsAtCompany: 3,
    verified: true,
    submittedAt: "2026-06-11T16:40:00Z"
  },
  {
    id: "18",
    companyName: "Netflix",
    tier: CompanyTier.TIER_1,
    role: RoleType.SOFTWARE_ENGINEER,
    levelCode: "Senior",
    standardLevel: "L3",
    baseSalary: 6500000,
    bonus: 0,
    equity: 2500000,
    totalCompensation: 9000000,
    location: "Mumbai, IN",
    yearsOfExperience: 8,
    yearsAtCompany: 1,
    verified: true,
    submittedAt: "2026-06-20T11:00:00Z"
  }
];
